[app]
title = YouTube Downloader Pro
package.name = youtube.downloader.pro
package.domain = com.youtube
version = 1.0
requirements = python3,kivy,pyjnius,android,yt-dlp,requests,urllib3,certifi,charset-normalizer,idna,pycryptodome,websockets,brotli,brotlicffi,ffmpeg
python.version = 3.9
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ttf
orientation = portrait
fullscreen = 0
wakelock = 1
android.permissions = INTERNET,ACCESS_NETWORK_STATE,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
android.api = 34
android.minapi = 21
android.sdk = 34
android.ndk = 25b
android.ndk_api = 21
android.arch = arm64-v8a
icon.filename = icon.png
presplash.filename = presplash.jpg
presplash.color = #FFFFFF
android.keystore = debug.keystore
android.keystore.password = android
android.keyalias = androiddebugkey
android.keyalias.password = android
android.allow_backup = true
android.sdk_download_timeout = 600
android.ndk_download_timeout = 600
p4a.branch = develop
android.accept_sdk_license = True
android.cmdline_tools_version = 11.0
android.sdk_path = /home/runner/android-sdk
android.skip_update = True

[buildozer]
log_level = 2
warn_on_root = 1
android.accept_sdk_license = true
